name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install -r docs/requirements.txt  # Install any extra dependencies for your Sphinx docs

      - name: Build the documentation
        run: |
          cd docs
          make html  # Adjust this if you use a different build command
        env:
          SPHINXOPTS: "-W"  # Treat warnings as errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html  # Path to the built documentation
